apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-prash
spec:
  arguments:
    parameters:
      - name: message
        value: hello prash
  templates:
    - name: whalesay-prasahant
      inputs:
        parameters:
          - name: demo
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
