apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-2
spec:
  arguments:
    parameters:
      - name: james
        value: hello wilson
  templates:
    - name: whalesay-moo
      inputs:
        parameters:
          - name: cops
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
